### ISSUE TITLE
Started jobs but no workers running

### ISSUE THREAD

**Issue by mark-99** [pricingassistant/mrq#105]
Hi - we're seeing a condition where we have some number of jobs in the "started" state, but no workers are running (they have all exited due to "burst mode" and the input queue being empty).

Any ideas what could cause this? For instance what if the worker consumes a job but then quits unexpectedly? And any suggestions how to defend against it, like requeue a job after some timeout, or via some manual call from the top-level script.

Thanks!

**Comment by sylvinus** [comment]
Hi @mark-99 !

Indeed, if a worker quits very abruptly, it might not have the time to set the job status to "interrupted". This is why we have written generic maintenance jobs that you should have in your scheduled tasks:
http://mrq.readthedocs.org/en/latest/jobs-maintenance/

Is that already the case?

**Comment by mark-99** [comment]
I spotted that just after I posted, yes it does look useful, although obviously I'd prefer to figure out why the worker is quitting unexpectedly, it's something like 30 out of 5000 so quite intermittent.

I haven't used the mrq-config.py so far, just command line params, so I guess I need to add that.

BTW unrelated, but what's the release schedule for the latest version of mrq to be the one you get from pip install?

**Comment by sylvinus** [comment]
The worker can quit unexpectedly for a variety of reasons:
 - the underlying OS kills the process (for instance because the OS is out of memory)
 - More generally, any time Python receives a signal that can't be ignored, for instance SIGKILL (`kill -9`)
 - the underlying OS/container shuts down
 - Python segfaults

Let us know if you found something! The next version to be released on pip should hopefully be 1.0, as mrq has now been very stable for quite some time.

**Comment by sylvinus** [comment]
Did the maintenance jobs cleanup the issue?

**Comment by mark-99** [comment]
We are still investigating the primary cause, ie why are some jobs failing (or perhaps even causing the worker to crash).

It does seem like RequeueStartedJobs will be helpful if we can't figure out what's causing the root problem.

**Comment by sylvinus** [comment]
@mark-99 any news? I'll be closing this issue if you don't find anything related to MRQ.

**Comment by mark-99** [comment]
There did seem to be something screwy with the jobs that went wrong, however it's still not clear how it managed to crash the worker (assuming that's what happened to get the DB into an inconsistent state).

Let's go ahead and close it, will let you know if I see anything more concrete in future.

Thanks.

**Comment by mark-99** [comment]
Ok this may be related - we have a job that calls subprocess.check_output(cmd) to launch a binary. It seems the binary crashed, and we also saw this callstack from mrq:


Traceback (most recent call last):
  File "/apps/homefs1/kocluster/python-local/mrq/worker.py", line 540, in perform_job
    job.perform()
  File "/apps/homefs1/kocluster/python-local/mrq/job.py", line 277, in perform
    result = self.task.run_wrapped(self.data["params"])
  File "/apps/homefs1/kocluster/python-local/mrq/task.py", line 17, in run_wrapped
    return self.run(params)
  File "/spare/condor/dir_3657364/tasks_metarunlist.py", line 19, in run
    pprint(cmd)
  File "/apps/homefs1/kocluster/venv-kapomega/lib/python2.7/pprint.py", line 59, in pprint
    printer.pprint(object)
  File "/apps/homefs1/kocluster/venv-kapomega/lib/python2.7/pprint.py", line 117, in pprint
    self._format(object, self._stream, 0, 0, {}, 0)
  File "/apps/homefs1/kocluster/venv-kapomega/lib/python2.7/pprint.py", line 214, in _format
    allowance + 1, context, level)
  File "/apps/homefs1/kocluster/venv-kapomega/lib/python2.7/pprint.py", line 222, in _format
    write(rep)
IOError: [Errno 32] Broken pipe

**Comment by sylvinus** [comment]
From this traceback it seems that whatever output your pprint() is writing to doesn't exist anymore. Doesn't seem to be related to MRQ.

**Comment by mark-99** [comment]
Ok. It's just a string so that's odd. We are also have a case where large numbers of jobs were in the 'started' state although far fewer workers were actually running, like this:

num_started: 31381, current_workers: 103

Code is this:

    num_started = get_queue_count(queue_name, ["started"])
    current_workers = get_num_workers(queue_name)

    def get_queue_count(queue_name, status_list):
        return mrq.context.connections.mongodb_jobs.mrq_jobs.count({"status": {"$in": status_list}, "queue": queue_name})

    def get_num_workers(queue_name):
        return mrq.context.connections.mongodb_jobs.mrq_workers.count({"status": {"$ne": "stop"}, "config.queues": queue_name})

**Comment by sylvinus** [comment]
Are your workers quitting abruptly in those cases ? If they do that the jobs will stay in "started" state until they are cleaned by one of the maintenance tasks

**Comment by sylvinus** [comment]
Closing this until further notice.
