### ISSUE TITLE
Can mrq loose tasks

### ISSUE THREAD

**Issue by DataGreed** [pricingassistant/mrq#107]
Hi!

I was wondering if MRQ uses redis pubsub or another machanism? The main question behind is – can it loose jobs if the consumer stops for some reason?

**Comment by sylvinus** [comment]
MRQ is designed to avoid losing any task. It can deal with various failure scenarios (from the workers or the databases) with maintenance tasks:
http://mrq.readthedocs.org/en/latest/jobs-maintenance/
