### ISSUE TITLE
Set MRQ_DEFAULT_JOB_TIMEOUT=1, Job in 'started' state, no work is done.

### ISSUE THREAD

**Issue by niksite** [pricingassistant/mrq#108]
When I set MRQ_DEFAULT_JOB_TIMEOUT env var - no matter 1 or 300 - the job is always 'started' and never got by any worker.

https://www.dropbox.com/s/t6zliqsidc9tt9o/Screenshot%202015-12-28%2021.18.40.png?dl=0

**Comment by sylvinus** [comment]
Hi @niksite!

Thanks for reporting this. Left me puzzled for a bit, but it turns out we were not type casting configuration values from environment variables. I've done a review of this area and added a test specifically for your case.

Thanks again!
