### ISSUE TITLE
How to pass args to _timed_set queue ?

### ISSUE THREAD

**Issue by alifanov** [pricingassistant/mrq#113]
Hi. I want to process some functions in specific time. But I pass dynamic arguments to them, like record_id to process. I couldn't find out how to do it.
Can you help me with this ?

**Comment by sylvinus** [comment]
Hi!

You have to do 2 things:

- Use the send_raw_task method with a dict with your arguments serialized in a string for the key, and the timestamp you want the task to be executed at for the value. Just like https://github.com/pricingassistant/mrq/blob/master/tests/test_raw.py#L28
- Then add an entry in your config with a `job_factory` that deserializes the key into the regular task arguments, like: https://github.com/pricingassistant/mrq/blob/master/tests/fixtures/config-raw1.py#L123

Let me know if that's clear enough!

**Comment by alifanov** [comment]
Hi. I've already implemented it with json.dumps()/json.loads().
But it will be better if you add this point in docs.
