### ISSUE TITLE
Concurrency Model

### ISSUE THREAD

**Issue by AlJohri** [pricingassistant/mrq#116]
Hi,

I'm having a little trouble understanding the concurrency model in mrq and its differences from celery.

I'm creating an io-bound application. Let's say we have thousands of urls and I need to simply grab the HTML and put it into Mongo.

My issue with Celery + Gevent is that, if I understand correctly, each worker is not running multiple greenlets in parallel. Instead it's pulling one message off of the queue at a time, finishing it, and grabbing the next. Even if it were able to get a few messages at a time, using a library like `requests` to make HTTP calls would still be blocking using gevent?

I read this in the mrq documentation which seems promising:
>You can run multiple workers in parallel. Each worker can also run multiple greenlets in parallel.
http://mrq.readthedocs.org/en/latest/get-started/#going-further

Could you help me understand how concurrency works in mrq vs celery? The word "concurrency" itself in the celery context I believe means multiple processes running per worker not multiple greenlets per process. It's a tad confusing.

**Comment by sylvinus** [comment]
Hi!

Sorry if it's confusing! We don't particularly try to follow the celery vocabulary.

You can indeed run multiple greenlets on just one process. it's the whole point of greenlets ;-)

Just do `mrq-worker --greenlets 10` and you will get one python process that will do 10 of your jobs in parallel.

Let me know if you have further questions!

**Comment by AlJohri** [comment]
Thanks for the speedy response @sylvinus !

I think I understand how it generally works now - I'm going to look at the web crawler example (https://github.com/pricingassistant/mrq/blob/master/examples/simple_crawler/crawler.py) and see if it fits my needs.

I have one question - you stressed that mrq is great for heterogenous environments in the README. When using celery, I can create a `gevent` worker and a `prefork` worker with different queues (io-bound, cpu-bound, for example). How does this work in mrq? I see that it uses `supervisord` but isn't it always using gevent as well? Like if I want 5 processes pulling from a cpu-bound queue, is each process internally using gevent with 1 greenlet?

**Comment by sylvinus** [comment]
Yes indeed, you can do that with `mrq-worker --processes 5 cpuboundqueue` :)
