### ISSUE TITLE
Worker does not restart after having "Reached max_jobs"

### ISSUE THREAD

**Issue by achauve** [pricingassistant/mrq#120]
I'm using the MAX_JOBS options to work around memory leaks and restart workers after MAX_JOBS jobs.

However currently the worker quits correctly but is not restarted by supervisord. 

Should the worker exit whit a special exit code when stopping after having reached max_jobs? I think it's currently just exiting with code 0 and thus supervisord doesn't restart it.

**Comment by sylvinus** [comment]
Good find! This should be added to the tests as well

**Comment by achauve** [comment]
It's fixed in 65c82c6a1917256092467123027b5cd14a140d2f, thanks!

**Comment by sylvinus** [comment]
thanks for reporting!

**Comment by ggueret** [comment]
Thanks for your report @achauve, tests are coming for that case.
