### ISSUE TITLE
Cherry-pick a few commits from tume/only_py3

### ISSUE THREAD

**Issue by sylvinus** [pricingassistant/mrq#122]
These 2 seem interesting:
https://github.com/tume/mrq/commit/97e2a53136acceba4ace5f043a2373f6001df323
https://github.com/tume/mrq/commit/ed40f7712811a010e70d72ff47d32fca048ca139

Thanks @tume!

**Comment by AlJohri** [comment]
just wanted to check in on py3 status. what issues remain?

**Comment by sylvinus** [comment]
Hi @AlJohri !

Actually that's it, we support python3 :) You can test our latest release 0.2.1 and let us know how it performs for you!

(This issue is about commits unrelated to python3 support)

**Comment by AlJohri** [comment]
Omg awesome. Will try now
