### ISSUE TITLE
On the processing sequence of parameters

### ISSUE THREAD

**Issue by ecebuzz** [pricingassistant/mrq#136]
Does mrq has any built-in mechanism to enforce a processing sequence of the parameter list?
For instance, given a parameter list ["a","b", "aa", "ab"], I would like parameters "a" and "b" to be processed first before parameters "aa" and "ab" are  processed.

**Comment by sylvinus** [comment]
Hi @ecebuzz ! Can you give an example? I am not sure which parameter list you are referring to.

Do you mean a queue in redis? (if so, a Lock would seem to be the solution here. Maybe setting max_concurrency=1 in your Task ? See https://github.com/pricingassistant/mrq/blob/master/mrq/task.py#L7)

**Comment by sylvinus** [comment]
Any news on this @ecebuzz ?

**Comment by sylvinus** [comment]
Closing until further explanation
