### ISSUE TITLE
Add a MAX_TIME to mrq-worker

### ISSUE THREAD

**Issue by ecebuzz** [pricingassistant/mrq#138]
MAX_TIME could serve as a hint to specify the maximum amount of time that the mrq-worker spends working on the jobs before quitting. This could compliment the functionality of MAX_JOBS. The mrq-worker could check both configuration settings before proceeding to decide whether it should process a new job or not.

**Comment by sylvinus** [comment]
That makes sense @ecebuzz, we'll accept a pull request for this if somebody submits one! Feel free to do so :)

**Comment by sylvinus** [comment]
Fixed by #152
