### ISSUE TITLE
mrq-dashboard initialization fails

### ISSUE THREAD

**Issue by ThetomekK** [pricingassistant/mrq#143]
Hi @ all,
installed mrq as readme tells, everything went well, but trying to launch the dashboard results in the following error. Does anyone knows, how to fix it. I'd like to use the dashboard alone.
Redis-server and mongodb server are running. I'm using latest python 2.7 interpreter.

Thanks in advance...

`Traceback (most recent call last):
  File "/home/tom3kk/.conda/envs/py27_mrq/bin/mrq-dashboard", line 7, in <module>
    from mrq.dashboard.app import main
  File "/home/tom3kk/.conda/envs/py27_mrq/lib/python2.7/site-packages/mrq/dashboard/app.py", line 29, in <module>
    set_current_config(cfg)
  File "/home/tom3kk/.conda/envs/py27_mrq/lib/python2.7/site-packages/mrq/context.py", line 82, in set_current_config
    patch_import()
  File "/home/tom3kk/.conda/envs/py27_mrq/lib/python2.7/site-packages/mrq/monkey.py", line 127, in patch_import
    import gevent.coros
  File "/home/tom3kk/.conda/envs/py27_mrq/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named coros`

**Comment by sylvinus** [comment]
Hi @ThetomekK ! 

Thanks for the report. You seem to be using an old version of MRQ. This bug has been fixed a while ago here:
https://github.com/pricingassistant/mrq/commit/c07ba9ecc708c7e5c756fa9602a5f878a81a4111#diff-3f84355d71c2db89b9089a75894c3e55

Cheers!

**Comment by dhamaniasad** [comment]
@sylvinus Still getting this on mrq==0.1.18

**Comment by sylvinus** [comment]
@dhamaniasad sorry we haven't pushed on pypi in a while. can you try the current master?

**Comment by dhamaniasad** [comment]
I can try that but I'm looking into mrq for a production scenario and so it
would be great if you could push to pypi as pinning to master is risky.

**Comment by sylvinus** [comment]
@dhamaniasad true; though you can also pin to a commit! (http://stackoverflow.com/questions/13685920/install-specific-git-commit-with-pip)

**Comment by dhamaniasad** [comment]
Pinning to master does make the issue go away it seems.

With Regards,
Asad Dhamani

**Comment by sylvinus** [comment]
@dhamaniasad can you check if your file `/home/tom3kk/.conda/envs/py27_mrq/lib/python2.7/site-packages/mrq/monkey.py` was properly updated? it it's up to date with master it shouldn't have a mention to `coros`.

**Comment by dhamaniasad** [comment]
It doesn't have that mention, yes. It works perfectly. Would be perfect if you could push the latest code to PyPI so this issue could be resolved without having to pip install with the git url :).
