### ISSUE TITLE
mrq should replace gevent.coros with gevent.lock as gevent.coros is removed starting 1.2a1

### ISSUE THREAD

**Issue by ecebuzz** [pricingassistant/mrq#153]
Taken from http://www.gevent.org/changelog.html
1.2a1 (Oct 27, 2016)

Incompatible Changes

Support for Python 2.6 has been removed. See pull request #766.
Remove module gevent.coros which was replaced by gevent.lock and has been deprecated since 1.0b2.
The internal implementation modules gevent.corecext and gevent.corecffi have been moved. Please import from gevent.core instead; this has always been the only documented place to import from.

**Comment by sylvinus** [comment]
@ecebuzz can you test with latest master? I think we already removed it.

**Comment by ecebuzz** [comment]
Sorry I only tested with an old version. Thanks
