### ISSUE TITLE
Problems with access to the dashboard behind Nginx reverse proxy with path in location

### ISSUE THREAD

**Issue by symonsoft** [pricingassistant/mrq#162]
Access to the dashboard through Nginx with path in localtion demands ugly excessive settings for the path substitution in response. That happens because absolute paths are used in all statics in mrq-dashboard.

Here is settings of my workaround:
```
    location /dashboard/ {
        proxy_pass http://localhost:5555/;

        sub_filter '"/static/' '"/dashboard/static/';
        sub_filter '"/workers' '"workers';
        sub_filter '"/api' '"api';
        sub_filter '"/#' '"#';
        sub_filter '\'/#' '\'#';

        sub_filter_once off;
        sub_filter_types text/html application/javascript;
    }
```

But I'm afraid that with version changes it could become broken. So, it would be great if mrq-dasboard statics start to work with relative paths.

**Comment by sylvinus** [comment]
Done with #122

**Comment by sylvinus** [comment]
Fixed in https://github.com/pricingassistant/mrq/commit/7e732f6083181ba197184b607d2a927163d25f3c
