### ISSUE TITLE
Best way to manage workers?

### ISSUE THREAD

**Issue by johnarnold** [pricingassistant/mrq#163]
Hi,

This is more of a "mailing list" type question but I didn't see a mailing list alias.

How do people manage their workers?  e.g. launching, restarting, monitoring?    We were thinking about writing code and daemonizing it for this purpose, but I gotta think someone has done this already?

Thanks,
John

**Comment by sylvinus** [comment]
No worries!

If you look at the 0.9.x branch, we're working on a new `mrq-agent` tool that will manage several `mrq-worker` processes on the same host. But you'll still have to manage the `mrq-agent` process :)

It depends on how you want to deploy. `supervisord` is a good choice for most users but there are many similar tools. If you use Docker then you just need to manage your containers and make sure they are orchestrated properly (see Docker Swarm, Kubernetes, ...)

Cheers!
