### ISSUE TITLE
backend modularity

### ISSUE THREAD

**Issue by johnarnold** [pricingassistant/mrq#165]
Hi,

This question is about the use of MongoDB.  I have MRQ working with MongoDB, but it does add "yet another" infrastructure asset that I have to manage/maintain and is not otherwise used in my software stack.

I tried using the Azure DocumentDB PaaS (which has MongoDB api support) but ran into some limitations related to indexing.

I found myself asking, given how little of the code actually has to do with mongodb, could the mongodb functions be factored out of the context/worker/... classes into a backend class?

Celery does it this way, with a base Backend class, and specific backends (redis, mongodb, etc) superclassing it.  The mongodb backend is only 300ish lines, which seems reasonable to maintain without bloating out MRQ into another Celery.

Give it some thought. I could contribute a DocumentDB native backend if there was a decent integration point, and i'm sure others could snap in backends very easily too.

Thanks,
John

**Comment by jkryanchou** [comment]
I though it might be trouble with gevent monkey patch. you could refer to the `mrq/monkey.py` mrq has patched so many mongo socks methods. If you switch another backend persistent database. You should implement another patch methods as mongo.

**Comment by sylvinus** [comment]
Hi John!

This is a good feedback, however for now we've decided to stick with the current implementation style and to the admittedly limited scope of this project.

Indeed, it may not be much code but adding an abstraction layer will make things more complex anyway, and add one more dimension to reason about. We really want to keep MRQ simple.

We've been very happy with the latest improvements made to mongodb lately so we are pretty confident it's still a good bet and can scale easily north of 100M jobs a day.

If you need more backends, I'd definitely recommend going with Celery.
