### ISSUE TITLE
best practice to create a group of jobs

### ISSUE THREAD

**Issue by functure** [pricingassistant/mrq#175]
While other jobs are being executed, I am required to create as much as 5000 jobs simultaneously and be able to monitor them separately (How many jobs are finished within scope of the initialization, how many failed etc.). They need to be separated evenly to multiple workers.

It seems to me that subpool is not a good solution for that. 

Best solution I can think of is writing results to a inititialization-specific mongodb collection via my own task class (store initialization metadata in another collection, catch all exceptions), compare finished and total to have a sense of how many jobs finished and do all of it with a raw queue so that I would not store the results twice. 

Another solution is to add the job family (initialization id) as parameter to each job. And send queries with that information.

Both of them are kind of workarounds and I am not sure what kind of problems I can face after implementation of those. 

I am looking for an advice.

**Comment by sylvinus** [comment]
Hi!

You could use a subqueue. Queue all your jobs on a queue named "group/[id]", run a worker with `mrq-worker group/` and then just monitor that queue.

Does that make sense?

**Comment by functure** [comment]
Thank you very much for your quick response! 

It does make sense. I am wondering is there any mechanism working like a trigger to know if every job in subqueue finished ?  

I need to know if the task group finished and execute some other instructions as a callback mechanism. I can create a separate job and check number of finished jobs periodically but there may be a more elegant method.

**Comment by sylvinus** [comment]
Currently there's no more elegant method, so periodical jobs are the way to go :)
