### ISSUE TITLE
Functionality for process managers like supervisor should be decoupled

### ISSUE THREAD

**Issue by saikatkumardey** [pricingassistant/mrq#190]
Supervisor doesn't have a stable python-3 package for now. I would like to use circusd or XYZ process manager.

**Comment by sylvinus** [comment]
Hi @saikatkumardey!

supervisor has been removed from the 0.9.x branch: https://github.com/pricingassistant/mrq/tree/0.9.x

You should test it, but by default MRQ will launch just one process and not use supervisord, so you can already use it with another process supervisor!
