### ISSUE TITLE
[Question] Use in Django

### ISSUE THREAD

**Issue by tboulogne** [pricingassistant/mrq#215]
Hello,

How could i use this into a django project please ?

Thanks for help.

Regards,

Thierry

**Comment by sylvinus** [comment]
Hello !

MRQ doesn't have an integration with Django. We recommend using Celery for that use case.

thanks!

**Comment by tboulogne** [comment]
Thx


De: Sylvain Zimmer <notifications@github.com>
Répondre: pricingassistant/mrq <reply@reply.github.com>
Date: 3 septembre 2019 at 02:00:46
À: pricingassistant/mrq <mrq@noreply.github.com>
Cc: Thierry BOULOGNE <tboulogne@tng-concepts.com>, Author <author@noreply.github.com>
Sujet:  Re: [pricingassistant/mrq] [Question] Use in Django (#215)  

Hello !

MRQ doesn't have an integration with Django. We recommend using Celery for that use case.

thanks!
