### ISSUE TITLE
Critical task, delay all another tasks

### ISSUE THREAD

**Issue by mmmcorpsvit** [pricingassistant/mrq#224]
I have very important task when all another must tasks must delay (after him finish) run critical task and resume normal thread loop.

How this can be implemented?

P.S. sorry my English

**Comment by azhard4int** [comment]
@mmmcorpsvit You can use sorted tasks and set the priority for the critical tasks higher. This way, your critical tasks will be processed first and other tasks later on.

**Comment by sylvinus** [comment]
You can also pass multiple queues to a worker:

```
$ mrq-worker highpriority lowpriority
```

This will start a single-process, single-greenlet worker with 2 queues. If you want to have multiple workers/processes with strict priorities, meaning a single task interrupting many low priority ones you will have to implement a lock in your task code!
