### ISSUE TITLE
Python 3.8 Syntax Warning

### ISSUE THREAD

**Issue by mmmcorpsvit** [pricingassistant/mrq#226]
C:\djangomrqtest\venv\lib\site-packages\mrq\worker.py:445: SyntaxWarning: "is" with a literal. Did you mean "=="?
`  if outcome is "wait" and dequeue_jobs == 0:`

more info:
https://adamj.eu/tech/2020/01/21/why-does-python-3-8-syntaxwarning-for-is-literal/
https://bugs.python.org/issue34850

**Comment by sylvinus** [comment]
Thanks!
