### ISSUE TITLE
Task event handlers

### ISSUE THREAD

**Issue by eddie** [pricingassistant/mrq#28]
Currently there is no way to handle a job timeout from within the task it's self, for jobs where timeouts are acceptable but need to cleanup, @sylvinus suggested we add event handlers for the on_retry, on_exception and on_timeout exceptions.

Just starting a discussion on the design/implementation of the event handlers :) 

on_retry(self, exception)
on_exception(self, exception)
on_timeout(self)

and perhaps

on_success(self)?

**Comment by sylvinus** [comment]
I've documented the current proper way to do it, in the new "Best practices" section of the docs:
https://github.com/pricingassistant/mrq/blob/master/docs/best-practices.md#using-your-own-base-task-class

For now we'll err on the side of caution and avoid adding this to the core API. We can reopen this if this becomes a common pattern.
