### ISSUE TITLE
load default config without argparse

### ISSUE THREAD

**Issue by eddie** [pricingassistant/mrq#51]
Parts of my codebase which require sending tasks are run from scripts which already use argparse.

I'd like to be able to pass config options for mrq to use in this case, without going through https://github.com/pricingassistant/mrq/blob/master/mrq/config.py#L9 add_parser_args

Splitting out add_parser_args from get_config and removing the dependency of default config being coupled to ArgumentParser would allow use to pass a dict to get_config with ease.  

Thoughts?

**Comment by sylvinus** [comment]
The preferred way of doing this is now to use `mrq.context.setup_context()`.

See https://github.com/pricingassistant/mrq/blob/master/tests/fixtures/standalone_script1.py for a simple example!
