### ISSUE TITLE
Add somes examples in the docs

### ISSUE THREAD

**Issue by sylvinus** [pricingassistant/mrq#63]
A simple crawler would be good to link at the end of the Get Started.

**Comment by robodude666** [comment]
+1. Very interested by what I see in Mr. Queue, however the lack of concrete examples is a little off-putting.

First time I ran across Mr. Queue months ago I ended up waving it off because the Get Started section makes it look like Jobs can be queued only via cli.

**Comment by sylvinus** [comment]
Definitely! Will have a prototype crawler up very soon.

**Comment by sylvinus** [comment]
@robodude666 any feedbacks on this?

**Comment by sylvinus** [comment]
You can also check out https://github.com/sylvinus/imgfab, which we'll include in the docs as an example
