### ISSUE TITLE
Supervisord template broken?

### ISSUE THREAD

**Issue by achauve** [pricingassistant/mrq#68]
When I run `mrq-worker` with `-p 2` and the default provided supervisord template, I get the error:

```
supervisor: couldn't chdir to /app: ENOENT
```

and if I provide a custom template without the line `directory=/app` it works fine.
What is this line supposed to do? (as there's no app/ directory in my application and supervisor doesn't seem to need it anyways).

Thanks

**Comment by sylvinus** [comment]
Thanks! 

`/app` was the path inside Docker (and on Heroku). I removed it from the template.
