### ISSUE TITLE
Workers failing to report Queues

### ISSUE THREAD

**Issue by eddie** [pricingassistant/mrq#74]
Whilst upgrading to 0.1.10 we noticed an issue in the dashboard where queues are not showing in the workers tab.. 

Can confirm this information isn't in the database

```
db.mrq_workers.find({}, {name:1, config:1})
{ "_id" : ObjectId("54e5d55f2431ff5cc80a00d7"), "config" : { "max_jobs" : 0, "processes" : 0, "name" : "", "queues" : [  "st_queue_a" ], "greenlets" : 20, "scheduler" : false }, "name" : "ip-" }
{ "_id" : ObjectId("54e5d5682431ff5cf648adb2"), "config" : { "max_jobs" : 0, "processes" : 0, "name" : "", "queues" : [  "st_queue_b" ], "greenlets" : 8, "scheduler" : false }, "name" : "ip-" }
{ "_id" : ObjectId("54e5d5882431ff5d3f2ba1c9"), "config" : { "max_jobs" : 0, "processes" : 0, "name" : "", "queues" : [  "st_queue_c" ], "greenlets" : 8, "scheduler" : false }, "name" : "ip-" }
{ "_id" : ObjectId("54e5d55c2431ff5cb9bc719a"), "config" : { "max_jobs" : 0, "processes" : 0, "scheduler" : false, "greenlets" : 50, "name" : "" }, "name" : "ip-" }
{ "_id" : ObjectId("54e5d5642431ff5cdef8ce38"), "config" : { "max_jobs" : 0, "processes" : 0, "scheduler" : false, "greenlets" : 30, "name" : "" }, "name" : "ip-" }
```

We run a customer worker script instead of mrq-worker as it allows us to work with our own config setup..  It's almost identical to mrq-worker with a couple of tweaks

```python
#!/usr/bin/env python
# -*- coding:utf-8 -*-
import os

# Needed to make getaddrinfo() work in pymongo on Mac OS X
# Docs mention it's a better choice for Linux as well.
# This must be done asap in the worker
if "GEVENT_RESOLVER" not in os.environ:
    os.environ["GEVENT_RESOLVER"] = "ares"

from gevent import monkey
monkey.patch_all()

import config
import sys

sys.path.insert(0, os.getcwd())

from mrq.utils import load_class_by_path
from mrq.context import set_current_config

....

    worker_class = load_class_by_path(cfg["worker_class"])
    set_current_config(cfg)

    w = worker_class()
    exitcode = w.work_loop()
    sys.exit(exitcode)
```
I have verified cfg is valid and contains 'queues', i.e cfg['queues'] = ["queue_names"]
We have also changed the redis_prefix and mongo db name to ensure a fresh test for this.. But problem persists.. 

![selection_003](https://cloud.githubusercontent.com/assets/2206948/6267018/1c3705ee-b838-11e4-8628-e48ea9a8c4a1.png)

Any help would be appreciated on this :)

Update: From tests, it looks like the workers that are the busiest don't get updated... Will keep looking

**Comment by sylvinus** [comment]
Hi Eddie,

I've looked over the code and the only way I can think of this happening is that you have a second `set_current_config()` later in your code that empties this configuration variable (maybe because it comes from a call to `get_config()` without `config_type=worker`?). It must be set when worker_class() is called because your worker seems to be running fine. So my guess is that it's emptied at some later point!

Let me know if that helps.

**Comment by sylvinus** [comment]
@eddie any news on this?

**Comment by eddie** [comment]
Hey @sylvinus we had quite a few problems with jobs hanging, so we've decided to move away from mrq/gevent at the moment.. Never did find the problem, sorry! Feel free to close :)

**Comment by sylvinus** [comment]
Oh sorry to hear that @eddie :/ Can you describe the behaviour of those hanging jobs?

**Comment by eddie** [comment]
We would hit a point where job's were not processing fast enough for our needs (we had sufficient workers/greenlets).. and looking in the dashboard we would see plenty of jobs marked as started but many hours ago.. for example "Started 10 hours ago".. and they would never get processed becaue of this.. 

I imagine the job got started but never reported back to mongo.. 

MRQ has worked great, I think we've just grown a bit- and are currently building our own workers :)

**Comment by sylvinus** [comment]
Jobs staying in "started" status can happen if worker processes are interrupted abruptly. That's why you need to add a few scheduled tasks to requeue them, as explained here:
http://mrq.readthedocs.org/en/latest/jobs-maintenance/

You were one of the first users of MRQ, sorry if that wasn't clear at the time! Thanks for all your help along the way and we hope to have you involved in the future again!

**Comment by eddie** [comment]
Thanks @sylvinus! Mr. Queue is great- just we're currently moving a bit faster than MRQ and have quite specific needs, and thanks again for your continued support, very much appreciated :)
