### ISSUE TITLE
dashboard/app.py  "use_with_reloader"  error

### ISSUE THREAD

**Issue by pianoboysai** [pricingassistant/mrq#79]
in dashboard/app.py, there is code:
"run_simple('', int(os.environ.get("PORT", 5555)), app, use_with_reloader=True)"

refer to latest werkzeug document
http://werkzeug.pocoo.org/docs/0.10/serving/

should instead "use_with_reloader" with "use_reloader"

**Comment by sylvinus** [comment]
Thanks!
