### ISSUE TITLE
Need full explaination of configuration variables.

### ISSUE THREAD

**Issue by eromoe** [pricingassistant/mrq#81]
Docs here http://mrq.readthedocs.org/en/latest/configuration/  only say a little.
I want to know how to set mongodb and other useful variables

**Comment by sylvinus** [comment]
Yes we definitely have to update the online doc.

For now you can either do `mrq-worker --help` or check https://github.com/pricingassistant/mrq/blob/master/mrq/config.py

**Comment by IAlwaysBeCoding** [comment]
I think https://github.com/pricingassistant/mrq/pull/91 and https://github.com/pricingassistant/mrq/pull/92 fixed this issue on the documentation issue. If there is anything else you would like me to explain, I'd be more than welcome to do a PR to fully fix this.  Lets get MrQ to version 1.0.0

**Comment by sylvinus** [comment]
Yep, we can definitely consider this as closed. Thanks a lot @IAlwaysBeCoding !

**Comment by IAlwaysBeCoding** [comment]
@sylvinus No problem,your project will be the brainchild of a project I have in mind, so it is definitely in my best interest to have MrQ ready for  "production" .Cheers!
