### ISSUE TITLE
missing dependecy?

### ISSUE THREAD

**Issue by oz123** [pricingassistant/mrq#83]
I was going through the code (didn't run it though) and I saw you refer to mongokit. 
However, I did not find a place where mongokit is referenced in one of the requirements files.

**Comment by sylvinus** [comment]
We monkey-patch MongoKit just in case you're actually using it. The code is wrapped in a try-except block so it's not a dependency:
https://github.com/pricingassistant/mrq/blob/master/mrq/monkey.py#L109
