### ISSUE TITLE
Use public python docker images in CI tests

### ISSUE THREAD

**Issue by iorlas** [pricingassistant/mrq#86]
Currently I use `python` docker image, which is common for most python+docker developers. With current CI configuration, you run tests within common ubuntu container, which is nice and tests code like on common configurations(Ubuntu LTS, yea). But! If developer uses docker, he will have no reasons to setup full ubuntu container, just python one, which is available for few **latest** releases of both branches.
So now I see a bug in `gevent 1.0.1` with `python>=2.7.9`, which blocks process from running by... import exception. And this but wasn't detected because of tests environment.
Yea, production will be ubuntu LTS in most cases, but what about developer environment?

**Comment by sylvinus** [comment]
This is a valid point. I think we'll indeed add a second Dockerfile and test it as well on CircleCI. I just have to see what is the best way to do that with them (in one build, or with multiple chained builds)

**Comment by sylvinus** [comment]
Decided against doing that. We can't test every different environment, and ubuntu is standard enough. If there are environment-specific bugs, please open issues and we'll see if it makes sense to fix them in MRQ.

thanks,
