### ISSUE TITLE
Ease run of jobs

### ISSUE THREAD

**Issue by iorlas** [pricingassistant/mrq#88]
Instead of queue_job(path, data), we should consider to use similar to celery style: `task.delay(data)` or `task.enqueue(data)`.

Also, since it is intended to be just one function in task, maybe we should do it... celery-way? Create decorator and write simple function - just as short way. Saves 1 indent and makes code easier to understand.

**Comment by iorlas** [comment]
Also, it could be awesome if we will make decorator to add scheduler tasks instead of using settings.

**Comment by sylvinus** [comment]
Thanks for your feedback!

We are a bit opposed the the "celery-way" of using decorators, because while it may be a little more convenient in some use cases, it requires the system to read all the code just to know what the timeout or the result TTL on a task is.

By using a centralized task metadata repository (in the settings), we can know the TTL, timeout and default queue for each job and that proves very useful when writing cleaning or maintenance tasks (see for instance https://github.com/pricingassistant/mrq/blob/master/mrq/basetasks/utils.py#L73)

That said, we'll happily consider other ways of making the task API friendlier if possible!

**Comment by iorlas** [comment]
But we can use `@task()` to populate global variable like centralized task metadata repository.

Also, I don't really understand why you need to set anything explicitly in one place like a settings one. Because numbers and things like queue, TTL, timeout etc... they can't make sense outside of tasks module/package context. One thought I had - it is handy when you have different workers.

So, you can collect metadata into global settings implicitly.

**Comment by sylvinus** [comment]
@iorlas, can you explain how you would collect the metadata from all the iterators without having to import all the task source files? (we have several hundreds of them)

**Comment by sylvinus** [comment]
@iorlas ?

**Comment by iorlas** [comment]
Wow, I was out of loop, sry. I can see 2 approaches to this problem:

  1. Assume you will import every task eventually(*yea, I know it is now true*), you can import everything at the start and... so it is easy to do. Just simple registry mechanism.

  2. Pregenerate `schema` like Rails does it with models. So... search for tasks.py or tasks package, import everything, save data, dump into schema, run workers, boom!

Actually I don't see a reason not to import all tasks into worker memory anyway. Anyway, you will import most apps parts as dependencies of some task modules.

**Comment by sylvinus** [comment]
Okay! Well, that's where we may have different requirements. Even for medium-scale codebases like ours, just loading code/modules (numpy, scipy, pandas are huge beasts) can require non-trivial amounts of memory, and we end up saving a lot if we only load them when required.

Closing this as we consider it a part of MRQ's design. Still, thanks for the feedback!

**Comment by iorlas** [comment]
But look at second point! I know that, you need this by design. So there is a second thing - tasks schema, which could be still collected automagicaly.
Then, save in as tasks_schema.py and use in workers. What's about that?

**Comment by sylvinus** [comment]
It's an interesting idea but it adds a step that is very likely to be forgotten when you add a task. I'm not sure it's worth it.

**Comment by iorlas** [comment]
You can run it within `run`. Also, you can simplify it by not importing it - by parsing files with python AST. So.. It may lead to tasks DSL, hehe.

But hey, I see a compromise: add decorator, which will populate tasks registry if it isn't registered yet(by path). So if you need to register task w/o import - you can still do it via settings. But if you can import task - it will be registered by decorator. What your thoughts?

**Comment by sylvinus** [comment]
Doesn't seem practical - a good practice is to deploy code read-only, and if you dump on your workers you risk having differences between them. Again, not sure any of this is worth the cost of just updating the config by hand when you have a task that doesn't use the default queues/timeouts.

**Comment by iorlas** [comment]
Second thing should be really good for both of us. Just add a decorator, which will register task if it is not registered. So it makes *almost* no difference in inner mrq logic.
