### ISSUE TITLE
Add ability run one scheduler task per time

### ISSUE THREAD

**Issue by iorlas** [pricingassistant/mrq#89]
Something like run-one.
This is a weakness of celery - we should rely on cache mechanism(lock/unlock) instead of actual check for job in current queue.

With mrq, it is simple - we should just ask mongodb for task with same path and params.

**Comment by sylvinus** [comment]
Hi @iorlas,

This is actually already supported via Raw Queues: http://mrq.readthedocs.org/en/latest/queues/

You can define a queue as a set (or sorted set) of unique parameters and that will make sure the task is only used once. We use that a lot and performance is really fast thanks to redis.
