### ISSUE TITLE
Need to fix mrq documentation online, formatting broke.

### ISSUE THREAD

**Issue by IAlwaysBeCoding** [pricingassistant/mrq#93]
My last, PR broke some of the formatting of the documenting on readthedocs.
http://mrq.readthedocs.org/en/latest/command-line/

Sorry about that. It looked good to me when I viewed it through github

**Comment by sylvinus** [comment]
No worries at all! RTD can be a little weird sometimes. I've made a couple fixes and things look good now! Thanks for the help!
