### ISSUE TITLE
"burst mode"

### ISSUE THREAD

**Issue by mark-99** [pricingassistant/mrq#97]
Hi - is there any equivalent to RQ's "burst mode"?  For a given batch job I'm creating and populating a dynamic queue (named user-pid-datetime) then launching workers on a Condor cluster. In RQ with burst mode, once the job queue is empty the workers will exit.

Is there any way to do this in MRQ?

**Comment by sylvinus** [comment]
Hi Mark,

We have a max-jobs option for the worker but you must know the amount of jobs in the queue in advance. However a burst-mode similar to RQ could be added fairly easily if you confirm you're interested in that feature!

Best,

**Comment by mark-99** [comment]
Awesome - thanks. Will try the patch asap.

BTW I had seen max-jobs but I don't think that can be made to work in this context - there's no way to tell how many jobs any given client will consume, and even a slight error would mean either unfinished jobs or clients keeping running.

**Comment by mark-99** [comment]
Hi - will this feature show up in the "pip install" version sometime? Thanks.
